name: Build Algeria Recharge GUI EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build self-contained EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-artifacts
          path: ./bin/Release/net8.0-windows/win-x64/publish/AlgeriaRechargeGui.exe
